-- CREATE TABLE IF NOT EXISTS EMAIL_NOTIFICATIONS (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     email TEXT NOT NULL,
--     received_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
--     historyID STRING NOT NULL
-- );

CREATE TABLE IF NOT EXISTS INGEST_CURSOR (
    source             TEXT PRIMARY KEY,
    history_id         INTEGER NOT NULL,
    received_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS NORMALIZED_SUBMISSIONS (
    id STRING PRIMARY KEY,
    SOURCE TEXT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    status TEXT NOT NULL,
    AUTHOR TEXT NOT NULL,
    ATTRIBUTION TEXT NOT NULL,
    IMAGE_PATHS TEXT NOT NULL,
    CAPTION TEXT NOT NULL
);
